services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
