services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
